language: python
python: 2.7
sudo: false
env:
  - TOX_ENV=py27 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py27
  - TOX_ENV=py33 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py33
  - TOX_ENV=py34 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py34
  - TOX_ENV=pypy CASS_DRIVER_NO_CYTHON=1

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
