language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.4.1"

sudo: false
env:
  - CASS_DRIVER_NO_CYTHON=1

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - pip install tox-travis
  - gem install danger --version '~> 5.0'

script:
  - tox
  - tox -e patched_loops
  - danger
